apps/posts/urls.py
# apps/posts/urls.py

# Django modules
from django.urls import path

# Locals
from apps.posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home'),
    path('posts/', views.posts_list, name='posts_list'),
    path('post/1', views.post_single, name='post_single'),
    path('search/', views.search, name='search'),
]

config/urls.py
# confit/urls.py

# Django modules
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# Django locals

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),

    # Tinymce
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/marketing/models.py
# apps/marketing/models.py

# Django modules
from django.db import models

# Create your models here.

class Signup(models.Model):
	email = models.EmailField()
	timestamp = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Singup"		
		verbose_name_plural = "Singup"		

	def __str__(self):
		return self.email

apps/posts/models.py
# apps/posts/models.py

# Django modules and third parties
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from tinymce.models import HTMLField

# Define User
User = get_user_model()


# Author model
class Author(models.Model):
	# Author has OneToOne relationship with the User model
	# An author is belong to a user
	user 			= models.OneToOneField(User,on_delete=models.CASCADE)
	profile_picture = models.ImageField()

	class Meta:
		verbose_name = 'Author'
		verbose_name_plural = 'Authors'

	def __str__(self):
		return self.user.username


# Category model
class Category(models.Model):
	title = models.CharField(max_length=50)

	class Meta:
		verbose_name = 'Category'
		verbose_name_plural = 'Categories'

	def __str__(self):
		return self.title


# Tag model
class Tag(models.Model):
	title 		= models.CharField(max_length=50)
	# Tag has ManyToOne relationship with Category.
	# Many tags can belong to a category. 
	category 	= models.ForeignKey(Category, on_delete=models.CASCADE)

	class Meta:
		verbose_name = 'Tag'
		verbose_name_plural = 'Tags'

	def __str__(self):
		return self.title


# Post model
class Post(models.Model):
	title 			= models.CharField(max_length=100)
	slug 			= models.SlugField(max_length=250)
	# overview 		= models.TextField()
	overview 		= HTMLField()
	timestamp 		= models.DateTimeField(auto_now_add=True)
	content 		= HTMLField()
	comment_count 	= models.IntegerField(default=0)
	view_count 		= models.IntegerField(default=0)
	# Post has ManyToOne relationship with Author.
	# Many posts can belong to an author. 	
	author 			= models.ForeignKey(Author, on_delete=models.CASCADE)
	thumbnail 		= models.ImageField()
	# Post has ManyToMany relationship with Category.
	# A post can have many categories.
	categories 		= models.ManyToManyField(Category)
	# Post has ManyToMany relationship with Tag.
	# A post can have many tags.
	tags 			= models.ManyToManyField(Tag)
	featured 		= models.BooleanField()

	class Meta:
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:post_single', kwargs={
			'id':self.id 
		})


# Gallery images
class Gallery(models.Model):
	title = models.CharField(max_length=100, blank=True, null=True)
	image = models.ImageField(upload_to='gallery/%Y/%m/%d')
	timestamp 		= models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = 'Gallery'
		verbose_name_plural = 'Galleries'

	def __str__(self):
		return self.title

apps/marketing/views.py
from django.shortcuts import render

# Create your views here.

apps/posts/views.py
# apps/posts/views.py

# Django modules
from django.shortcuts import render
from django.db.models import Count, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Locals
from apps.posts.models import Author, Category, Post, Tag, Gallery
from apps.marketing.models import Signup

# Create your views here.

def search(request):

	# Load all post objects
    queryset = Post.objects.all()
    # Get and query all post objects
    query = request.GET.get('q')

    # If there is query, filter them
    # by title or overview and if there are
    # the same objects showed by title and overview,
    # use distinct to distinguished them.
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()

    context = {
        'queryset': queryset
    }
    return render(request, 'search_results.html', context)

def index(request):

	# Grab all the posts that has featured as true
	featured_posts = Post.objects.filter(featured=True)

	# Testing
	# print(featured_posts)

	# Grab 3 latest posts and render them based on LIFO
	latest_posts = Post.objects.order_by('-timestamp')[0:3]
	
	# Testing
	# print(latest_posts)

	# Subscribe Newsletter (without security)
	if request.method == "POST":
		email = request.POST["email"]
		new_signup = Signup()
		new_signup.email = email
		new_signup.save()
	
	# # Gallery
	# Grab 3 latest images and render them based on LIFO
	images_list = Gallery.objects.order_by('-timestamp')[0:4]

	context = {
		'featured_posts': featured_posts,
		'latest_posts': latest_posts,
		'images_list': images_list
	}

	return render(request, 'index.html', context)


# Category count view
def get_category_count():
	queryset = Post.objects.values('categories__title').annotate(Count('categories__title'))
	return queryset

# Tag count view
def get_tag_count():
	queryset = Post.objects.values('tags__title').annotate(Count('tags__title'))
	return queryset


def posts_list(request):

	# Grab all posts
	posts_list = Post.objects.all()

	# Grab 3 posts based on LIFO
	posts_latest = Post.objects.order_by('-timestamp')[0:3]

	# Count the category
	category_count = get_category_count()

	# Count the tag
	tag_count = get_tag_count()

	# Pagination
	# Set number of post to view per page
	paginator = Paginator(posts_list, 3)
	# Page request pariable
	# -> 127.0.0.1:8000/blog/?page=3	
	page_request_var = 'page' # <-- page=3
	page = request.GET.get(page_request_var)  # <-- page=3
	# Do some check
	try:
		paginated_queryset = paginator.page(page)
	# if request was not integer: 
	# --> 127.0.0.1:8000/blog/?page=fdfkdfkdfk
	# then return to page 1 or home page		
	except PageNotAnInteger: 
		paginated_queryset = paginator.page(1)
	# if request was empty page: 
	# --> 127.0.0.1:8000/blog/?page=
	# then return number of pages in queryset
	except EmptyPage:
		paginated_queryset = paginator.page(paginator.num_pages)

	context = {
		# 'posts_list':posts_list, # see line 102 ---> 'posts_list':paginated_queryset,
		'posts_latest':posts_latest,
		'category_count':category_count,
		'tag_count':tag_count,

		# Pagination
		'posts_list':paginated_queryset,
		'page_request_var':page_request_var,
	} 
	
	return render(request, 'posts/posts-list.html', context)


def post_single(request):
	return render(request, 'post-single.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% include 'shared/head.html' %}
    <title>Any Blog | {% block title %}{{block.super}}{% endblock title%}</title>
  </head>
  <body>
    <!-- Header -->
    {% include 'shared/header.html' %}

    {% block content %}
    {% endblock content %}
    
    <!-- Page Footer-->
    {% include 'shared/footer.html' %}
    
    <!-- JavaScript files-->
    {% include 'shared/scripts.html' %}
  </body>
</html>

templates/blog.html
<!-- templates/index.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog{% endblock title%}

{% block content %}

    <div class="container">
      <div class="row">

        <!-- Latest Posts and Pagination-->
        <main class="posts-listing col-lg-8"> 
          <div class="container">

            <!-- Posts -->
            {% include 'blog/posts.html' %}

            <!-- Pagination -->
            {% include 'blog/pagination.html' %}

          </div>
        </main>
        <!-- END Latest Posts and Pagination -->

        <!-- Aside -->
        <aside class="col-lg-4">

          <!-- Search-->
          {% include 'shared/aside-search.html' %}

          <!-- Latest posts-->
          {% include 'shared/aside-latest-posts.html' %}

          <!-- Categories-->
          {% include 'shared/aside-categories.html' %}

          <!-- Tags -->
          {% include 'shared/aside-tags.html' %}

        </aside>
        <!-- END Aside -->

      </div>
    </div>

{% endblock content %}

templates/blog/latest-posts.html
{% load static %}
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">
              <a href="#">
                <div class="item d-flex align-items-center">
                  <div class="image">
                    <img src="{% static 'img/small-thumbnail-1.jpg' %}" 
                    alt="..." class="img-fluid">
                  </div>
                  <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> 500</div>
                      <div class="comments"><i class="icon-comment"></i>12</div>
                    </div>
                  </div>
                </div>
              </a>
              <a href="#">
                <div class="item d-flex align-items-center">
                  <div class="image">
                    <img src="{% static 'img/small-thumbnail-2.jpg' %}" 
                    alt="..." class="img-fluid">
                  </div>
                  <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> 500</div>
                      <div class="comments"><i class="icon-comment"></i>12</div>
                    </div>
                  </div>
                </div>
              </a>
              <a href="#">
                <div class="item d-flex align-items-center">
                  <div class="image">
                    <img src="{% static 'img/small-thumbnail-3.jpg' %}" 
                    alt="..." class="img-fluid">
                  </div>
                  <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> 500</div>
                      <div class="comments"><i class="icon-comment"></i>12</div>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>

templates/blog/search.html
{% load static %}
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input type="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>

templates/blog/tags.html
{% load static %}
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#" class="tag">#Business</a>
              </li>
              <li class="list-inline-item">
                <a href="#" class="tag">#Technology</a>
              </li>
              <li class="list-inline-item">
                <a href="#" class="tag">#Fashion</a>
              </li>
              <li class="list-inline-item">
                <a href="#" class="tag">#Sports</a>
              </li>
              <li class="list-inline-item">
                <a href="#" class="tag">#Economy</a>
              </li>
            </ul>
          </div>

templates/home/divider.html
{% load static %}
    <section style="background: url({% static 'img/divider-bg.jpg' %}); background-size: cover; background-position: center bottom" class="divider">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h2>---Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</h2><a href="#" class="hero-link">View More</a>
          </div>
        </div>
      </div>
    </section>

templates/home/featured-posts.html
{% load static %}
    <section class="featured-posts no-padding-top">
      <div class="container">

        {% for object in featured_posts %}
        <!-- Post-->
        <div class="row d-flex align-items-stretch">

          {% if not forloop.first and not forloop.last %}
          <!-- post image -->
          <div class="image col-lg-5">
            <img src="{{ object.thumbnail.url }}" alt="...">
          </div>
          <!-- end post image -->
          {% endif %}

          <!-- post text -->
          <div class="text col-lg-7">
            <div class="text-inner d-flex align-items-center">
              <div class="content">
                <header class="post-header">
                  
                  <!-- category -->
                  <div class="category">
                    {% for cat in object.categories.all %}
                    <a href="#">{{ cat.title|title }}</a>
                    {% endfor %}
                  </div>
                  <!-- end category -->

                  <a href="{% url 'posts:post_single' %}">
                    <h2 class="h4">{{ object.title|title }}</h2>
                  </a>
                </header>
                <p>{{ object.overview|slice:"200"}}</p>
                <footer class="post-footer d-flex align-items-center">
                  <a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar">
                      <img src="{{ object.author.profile_picture.url }}" 
                        alt="..." class="img-fluid">
                      </div>
                    <div class="title">
                      <span>{{ object.author|title}}</span>
                    </div>
                  </a>
                  <div class="date">
                    <i class="icon-clock"></i>{{ object.timestamp|timesince|title }} ago
                  </div>
                  <div class="comments">
                    <i class="icon-comment"></i>{{ object.comment_count }}
                  </div>
                </footer>
              </div>
            </div>
          </div>
          <!-- post text -->

          {% if forloop.first or forloop.last %}
          <!-- post image -->
          <div class="image col-lg-5">
            <img src="{{ object.thumbnail.url }}" alt="...">
          </div>
          <!-- end post image -->
          {% endif %}

        </div>
        <!-- END Post -->
        {% endfor %}

      </div>
    </section>

templates/home/gallery.html
{% load static %}
    <section class="gallery no-padding">    
      <div class="row">

        {% for gal_image in images_list %}
        <!-- Gallery -->
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item">
            <a href="{{ gal_image.image.url }}" 
              data-fancybox="gallery" class="image">
              <img src="{{ gal_image.image.url }}" 
                alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center">
                <i class="icon-search"></i>
              </div>
            </a>
          </div>
        </div>
        <!-- END Gallery -->
        {% endfor %}
        
      </div>
    </section>

templates/home/hero.html
{% load static %}
    <section style="background: url({% static 'img/hero.jpg' %}); background-size: cover; background-position: center center" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <h1>Bootstrap 4 Blog - A free template by Bootstrap Temple</h1><a href="#" class="hero-link">Discover More</a>
          </div>
        </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>
      </div>
    </section>

templates/home/intro.html
{% load static %}
    <section class="intro">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <h2 class="h3">Some great intro here</h2>
            <p class="text-big">Place a nice <strong>introduction</strong> here <strong>to catch reader's attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.</p>
          </div>
        </div>
      </div>
    </section>

templates/home/latest-posts.html
{% load static %}
    <section class="latest-posts"> 
      <div class="container">
        <header> 
          <h2>Latest from the blog</h2>
          <p class="text-big">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </header>
        <div class="row">

          {% for object in latest_posts %}
          <!-- Latest post -->
          <div class="post col-md-4">
            <div class="post-thumbnail">
              <a href="post.html">
                <img src="{{ object.thumbnail.url }}" 
                  alt="..." class="img-fluid">
              </a>
            </div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date">{{ object.timestamp }}</div>
                <div class="category">
                  <a href="#">{{ object.category }}</a>
                </div>
              </div><a href="post.html">
                <h3 class="h4">{{ object.title|title }}</h3></a>
              <p class="text-muted">{{ object.overview|slice:"200"|title }}</p>
            </div>
          </div>
          <!-- END Latest post -->
          {% endfor %}
        </div>
      </div>
    </section>

templates/home/newsletter.html
{% load static %}
    <section class="newsletter no-padding-top">    
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Subscribe to Newsletter</h2>
            <p class="text-big">Lorem ipsum dolor sit amet, 
              consectetur adipisicing elit, sed do eiusmod 
              tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="col-md-8">
            <div class="form-holder">
              <form action="." method="POST">
                
                {% csrf_token %}

                <div class="form-group">
                  <input 
                    type="email" 
                    name="email" 
                    id="email" 
                    placeholder="Type your email address">

                  <button type="submit" class="submit">Subscribe</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

templates/index.html
<!-- templates/index.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title%}

{% block content %}

    <!-- Hero Section-->
    {% include 'home/hero.html' %}

    <!-- Intro Section-->
    {% include 'home/intro.html' %}

    <!-- Featured posts -->
    {% include 'home/featured-posts.html' %}

    <!-- Divider Section-->
    {% include 'home/divider.html' %}

    <!-- Latest Posts -->
    {% include 'home/latest-posts.html' %}

    <!-- Newsletter Section-->
    {% include 'home/newsletter.html' %}
    
    <!-- Gallery Section-->
    {% include 'home/gallery.html' %}

{% endblock content %}

templates/posts-list.html
<!-- templates/posts-list.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog{% endblock title%}

{% block content %}

    <div class="container">
      <div class="row">

        <!-- Latest Posts and Pagination-->
        <main class="posts-listing col-lg-8"> 
          <div class="container">

            <!-- Posts -->
            {% include 'posts/posts.html' %}

            <!-- Pagination -->
            {% include 'posts/pagination.html' %}

          </div>
        </main>
        <!-- END Latest Posts and Pagination -->

        <!-- Aside -->
        <aside class="col-lg-4">

          <!-- Search-->
          {% include 'shared/aside-search.html' %}

          <!-- Latest posts-->
          {% include 'shared/aside-latest-posts.html' %}

          <!-- Categories-->
          {% include 'shared/aside-categories.html' %}

          <!-- Tags -->
          {% include 'shared/aside-tags.html' %}

        </aside>
        <!-- END Aside -->

      </div>
    </div>

{% endblock content %}

templates/posts/inc/categories.html
{% load static %}
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            <div class="item d-flex justify-content-between">
              <a href="#">Growth</a><span>12</span>
            </div>
            <div class="item d-flex justify-content-between">
              <a href="#">Local</a><span>25</span>
            </div>
            <div class="item d-flex justify-content-between">
              <a href="#">Sales</a><span>8</span>
            </div>
            <div class="item d-flex justify-content-between">
              <a href="#">Tips</a><span>17</span>
            </div>
            <div class="item d-flex justify-content-between">
              <a href="#">Local</a><span>25</span>
            </div>
          </div>

templates/posts/inc/pagination.html
{% load static %}
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">

                <!-- Previous page -->
                {% if posts_list.has_previous %}
                <li class="page-item">
                  <a href="?{{ page_request_var }}={{ posts_list.previouse_page_number }}" class="page-link"> 
                    <i class="fa fa-angle-left"></i>
                  </a>
                </li>
                {% endif %}
                <!-- End Previous page -->

                <!-- The actual page numbers -->
                <li class="page-item">
                  <a href="#" class="page-link active">
                  {{ posts_list.number }}
                  </a>
                </li>
                <!-- End The actual page numbers -->

                <!-- Next page -->
                {% if posts_list.has_next %}
                <li class="page-item">
                  <a href="?{{ page_request_var }}={{ posts_list.next_page_number }}" class="page-link"> 
                    <i class="fa fa-angle-right"></i>
                  </a>
                </li>
                {% endif %}
                <!-- End Next page -->
                
              </ul>
            </nav>

templates/posts/inc/posts.html
{% load static %}
            <div class="row">

              {% for object in posts_list %}
              <!-- Post -->
              <div class="post col-xl-6">
                <div class="post-thumbnail">
                  <a href="{% url 'posts:post_single' %}">
                    <img src="{{ object.thumbnail.url }}" 
                    alt="..." class="img-fluid">
                  </a>
                </div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{ object.timestamp }}</div>
                    <div class="category">
                      {% for cat in object.categories.all %}
                      <a href="#">{{ cat.title|title }}</a>
                      {% endfor %}
                    </div>
                  </div><a href="{% url 'posts:post_single' %}">
                    <h3 class="h4">{{ object.title|title }}</h3></a>
                  <p class="text-muted">{{ object.overview|slice:"200"|striptags}}</p>
                  <footer class="post-footer d-flex align-items-center">
                    <a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar">
                        <img src="{{ object.author.profile_picture.url }}" 
                        alt="..." class="img-fluid">
                      </div>
                      <div class="title"><span>{{ object.author|title}}</span></div>
                    </a>
                    <div class="date"><i class="icon-clock"></i> {{ object.timestamp|timesince}} ago</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ object.comment_count }}</div>
                  </footer>
                </div>
              </div>
              <!-- END Post -->
              {% endfor %}
              
            </div>

templates/posts/posts-list.html
<!-- templates/posts-list.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog{% endblock title%}

{% block content %}

    <div class="container">
      <div class="row">

        <!-- Latest Posts and Pagination-->
        <main class="posts-listing col-lg-8"> 
          <div class="container">

            <!-- Posts -->
            {% include 'posts/inc/posts.html' %}

            <!-- Pagination -->
            {% include 'posts/inc/pagination.html' %}

          </div>
        </main>
        <!-- END Latest Posts and Pagination -->

        <!-- Aside -->
        <aside class="col-lg-4">

          <!-- Search-->
          {% include 'shared/aside-search.html' %}

          <!-- Latest posts-->
          {% include 'shared/aside-latest-posts.html' %}

          <!-- Categories-->
          {% include 'shared/aside-categories.html' %}

          <!-- Tags -->
          {% include 'shared/aside-tags.html' %}

        </aside>
        <!-- END Aside -->

      </div>
    </div>

{% endblock content %}

templates/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2>This is the results of your search</h2>

{% for post in queryset %}
    <a href="{{ posts.get_absolute_url }}">{{ post.title }}</a>
    <br />

{% endfor %}

{% endblock %}

templates/shared/aside-categories.html
{% load static %}
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>

            {% for cat in category_count %}
            <div class="item d-flex justify-content-between">
              <a href="#">{{ cat.categories__title|title }}</a>
              <span>{{ cat.categories__title__count }}</span>
            </div>
            {% endfor %}

          </div>

templates/shared/aside-latest-posts.html
{% load static %}
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">

              {% for object in posts_latest %}
              <!-- Latest post -->
              <a href="#">
                <div class="item d-flex align-items-center">
                  <div class="image">
                    <img src="{{ object.thumbnail.url }}" 
                    alt="..." class="img-fluid">
                  </div>
                  <div class="title"><strong>{{ object.title|title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{ object.view_count }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ object.comment_count }}</div>
                    </div>
                  </div>
                </div>
              </a>
              <!-- END Latest post -->
              {% endfor %}
            </div>
          </div>

templates/shared/aside-search.html
{% load static %}
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="{% url 'posts:search' %}" class="search-form">
              <div class="form-group">
                <input type="text" name="q" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>

templates/shared/header.html
{% load static %}

    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="#">
                  <div class="form-group">
                    <input type="search" name="search" id="search" 
                    	placeholder="What are you looking for?">
                    <button type="submit" class="submit">
                    	<i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="{% url 'posts:home' %}" class="navbar-brand">Any Blog</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" 
            	aria-controls="navbarcollapse" aria-expanded="false" 
            	aria-label="Toggle navigation" class="navbar-toggler">
            	<span></span><span></span><span></span>
            </button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
              	<a href="{% url 'posts:home' %}" class="nav-link active ">Home</a>
              </li>
              <li class="nav-item">
              	<a href="{% url 'posts:posts_list' %}" class="nav-link ">Blog</a>
              </li>
              <li class="nav-item">
              	<a href="{% url 'posts:post_single' %}" class="nav-link ">Post</a>
              </li>
              <li class="nav-item">
              	<a href="#" class="nav-link ">Contact</a>
              </li>
            </ul>
            <div class="navbar-text">
            	<a href="#" class="search-btn">
            		<i class="icon-search-1"></i>
            	</a>
            </div>
            <ul class="langs navbar-text">
            	<a href="#" class="active">EN</a>
            	<span></span><a href="#">ES</a>
            </ul>
          </div>
        </div>
      </nav>
    </header>